/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taxi_graphique;

import javax.swing.JOptionPane;
import taxi_DAO.Location_taxi_DAO;
import taxi.metier.Location_taxi;
import java.sql.*;
import java.time.LocalDate;
import java.util.*;
import taxi.metier.Client_taxi;
import taxi.metier.Location_taxi;

/**
 *
 * @author KAmgo
 */
public class CreaLocation extends javax.swing.JPanel {

    /**
     * Creates new form Crealocation
     */
    Location_taxi_DAO locationDAO=null;
    public CreaLocation() {
        initComponents();
    }

    public void setClientDAO(Location_taxi_DAO locationDAO){
        this.locationDAO=locationDAO;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbldateloc = new javax.swing.JLabel();
        llblnumlocation = new javax.swing.JLabel();
        lblkmtotal = new javax.swing.JLabel();
        lblacompte = new javax.swing.JLabel();
        lblidclient = new javax.swing.JLabel();
        txtnumtaxi = new javax.swing.JTextField();
        txtkmtotal = new javax.swing.JTextField();
        txtdateloc = new javax.swing.JTextField();
        txtacompte = new javax.swing.JTextField();
        txtidclient = new javax.swing.JTextField();
        btcreate = new javax.swing.JButton();
        lblidtaxi = new javax.swing.JLabel();
        txtidtaxi = new javax.swing.JTextField();
        iblidadrdebut = new javax.swing.JLabel();
        txtidadrdebut = new javax.swing.JTextField();
        iblidadrfin = new javax.swing.JLabel();
        txtidardfin = new javax.swing.JTextField();
        ibltotal = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();

        lbldateloc.setText("date location");

        llblnumlocation.setText("numéro de location");

        lblkmtotal.setText("km_total");

        lblacompte.setText("acompte");

        lblidclient.setText("idclient");

        txtnumtaxi.setEditable(false);
        txtnumtaxi.setMinimumSize(new java.awt.Dimension(50, 20));
        txtnumtaxi.setNextFocusableComponent(txtdateloc);
        txtnumtaxi.setPreferredSize(new java.awt.Dimension(150, 30));
        txtnumtaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumtaxiActionPerformed(evt);
            }
        });

        txtkmtotal.setMinimumSize(new java.awt.Dimension(50, 20));
        txtkmtotal.setNextFocusableComponent(txtacompte);
        txtkmtotal.setPreferredSize(new java.awt.Dimension(150, 30));
        txtkmtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkmtotalActionPerformed(evt);
            }
        });

        txtdateloc.setMinimumSize(new java.awt.Dimension(50, 20));
        txtdateloc.setNextFocusableComponent(txtkmtotal);
        txtdateloc.setPreferredSize(new java.awt.Dimension(150, 30));
        txtdateloc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatelocActionPerformed(evt);
            }
        });

        txtacompte.setMinimumSize(new java.awt.Dimension(50, 20));
        txtacompte.setNextFocusableComponent(txtidclient);
        txtacompte.setPreferredSize(new java.awt.Dimension(150, 30));
        txtacompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtacompteActionPerformed(evt);
            }
        });

        txtidclient.setMinimumSize(new java.awt.Dimension(50, 20));
        txtidclient.setPreferredSize(new java.awt.Dimension(150, 30));

        btcreate.setText("création");
        btcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcreateActionPerformed(evt);
            }
        });

        lblidtaxi.setText("id_taxi");

        iblidadrdebut.setText("idadrdebut");

        iblidadrfin.setText("id_adresse_fin");

        ibltotal.setText("total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btcreate)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblkmtotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(iblidadrfin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(iblidadrdebut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblidtaxi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(llblnumlocation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbldateloc, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblacompte, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblidclient, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ibltotal))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtidclient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtacompte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtkmtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtnumtaxi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtdateloc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtidtaxi)
                            .addComponent(txtidadrdebut)
                            .addComponent(txtidardfin)
                            .addComponent(txttotal))))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(llblnumlocation)
                    .addComponent(txtnumtaxi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldateloc)
                    .addComponent(txtdateloc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblkmtotal)
                    .addComponent(txtkmtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblacompte)
                    .addComponent(txtacompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibltotal)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidclient)
                    .addComponent(txtidclient, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblidtaxi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidtaxi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblidadrdebut, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidadrdebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidardfin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblidadrfin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btcreate)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtnumtaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumtaxiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumtaxiActionPerformed

    private void btcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcreateActionPerformed
     try{  
      String dateloc = txtdateloc.getText();
        int day = Integer.parseInt(dateloc.substring(1, 2));
        int month = Integer.parseInt(dateloc.substring(3, 5));
        int year = Integer.parseInt(dateloc.substring(6, 10));
        System.out.println("Nous sommes le "+day+" "+month+" "+year);
        LocalDate date = LocalDate.of(year, month, day);
        System.out.println(date);
       int kmtotal=Integer.parseInt(txtkmtotal.getText());
       int acompte=Integer.parseInt(txtacompte.getText());
       int total=Integer.parseInt(txttotal.getText());
       int idclient=Integer.parseInt(txtidclient.getText());
       int idtaxi=Integer.parseInt(txtidtaxi.getText());
       int idadrdebut=Integer.parseInt(txtidadrdebut.getText());
       int idadrfin=Integer.parseInt(txtidardfin.getText());
      
       Location_taxi taxi = new Location_taxi(0,date,kmtotal,acompte,total,idclient,idtaxi,idadrdebut,idadrfin);
       taxi=locationDAO.create(taxi);
       txtnumtaxi.setText(""+taxi.getIdtaxi());
       JOptionPane.showMessageDialog(this,"location créé","succès",JOptionPane.INFORMATION_MESSAGE);
       
     }
     catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
     }
               
    }//GEN-LAST:event_btcreateActionPerformed

    private void txtdatelocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatelocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatelocActionPerformed

    private void txtkmtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkmtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkmtotalActionPerformed

    private void txtacompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtacompteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtacompteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcreate;
    private javax.swing.JLabel iblidadrdebut;
    private javax.swing.JLabel iblidadrfin;
    private javax.swing.JLabel ibltotal;
    private javax.swing.JLabel lblacompte;
    private javax.swing.JLabel lbldateloc;
    private javax.swing.JLabel lblidclient;
    private javax.swing.JLabel lblidtaxi;
    private javax.swing.JLabel lblkmtotal;
    private javax.swing.JLabel llblnumlocation;
    private javax.swing.JTextField txtacompte;
    private javax.swing.JTextField txtdateloc;
    private javax.swing.JTextField txtidadrdebut;
    private javax.swing.JTextField txtidardfin;
    private javax.swing.JTextField txtidclient;
    private javax.swing.JTextField txtidtaxi;
    private javax.swing.JTextField txtkmtotal;
    private javax.swing.JTextField txtnumtaxi;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
