/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taxi_graphique;

import dbconnect.dbconnexion;
import java.awt.CardLayout;
import java.sql.Connection;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import taxi_DAO.Vehicule_taxi_DAO;
import taxi.metier.Vehicule_taxi;

/**
/**
 *
 * @author Kamgo
 */
public class GestionTaxi extends javax.swing.JFrame {

    /**
     * Creates new form GestionTaxi
     */
    CardLayout cardl;
    public GestionTaxi() {
        initComponents();
         cardl=(CardLayout)this.getContentPane().getLayout();
        cardl.show(this.getContentPane(), "card6");

       Connection dbConnect = dbconnexion.getConnection();
        if (dbConnect == null) {
            System.out.println("connection invalide");
            JOptionPane.showMessageDialog(this,"connexion invalide","ERREUR",JOptionPane.ERROR_MESSAGE);
        }
         
    Vehicule_taxi_DAO taxiDAO = new Vehicule_taxi_DAO();
    taxiDAO.setConnection(dbConnect);
    creaTaxi1.setClientDAO(taxiDAO);
    rechidtaxi1.setClientDAO(taxiDAO);
    rechimmatriculation1.setClientDAO(taxiDAO);
    rechDescription1.setClientDAO(taxiDAO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rechimmatriculation1 = new taxi_graphique.Rechimmatriculation();
        creaTaxi1 = new taxi_graphique.CreaTaxi();
        rechidtaxi1 = new taxi_graphique.Rechidtaxi();
        rechDescription1 = new taxi_graphique.RechDescription();
        fond1 = new taxi_graphique.fond();
        creaLocation1 = new taxi_graphique.CreaLocation();
        jMenuBar1 = new javax.swing.JMenuBar();
        menutaxi = new javax.swing.JMenu();
        itemcrea = new javax.swing.JMenuItem();
        itemrechnum = new javax.swing.JMenuItem();
        itemrechdescription = new javax.swing.JMenuItem();
        itemrechimmatricule = new javax.swing.JMenuItem();
        menulocation = new javax.swing.JMenu();
        itemcrealocation = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(rechimmatriculation1, "cardrechimmatriculation");
        getContentPane().add(creaTaxi1, "card3");
        getContentPane().add(rechidtaxi1, "cardrechid");
        getContentPane().add(rechDescription1, "card5");

        javax.swing.GroupLayout fond1Layout = new javax.swing.GroupLayout(fond1);
        fond1.setLayout(fond1Layout);
        fond1Layout.setHorizontalGroup(
            fond1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        fond1Layout.setVerticalGroup(
            fond1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        getContentPane().add(fond1, "card6");
        getContentPane().add(creaLocation1, "card7");

        menutaxi.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        menutaxi.setText("Taxi");

        itemcrea.setBackground(new java.awt.Color(255, 255, 0));
        itemcrea.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        itemcrea.setForeground(new java.awt.Color(255, 51, 51));
        itemcrea.setText("crée");
        itemcrea.setBorder(new javax.swing.border.MatteBorder(null));
        itemcrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemcreaActionPerformed(evt);
            }
        });
        menutaxi.add(itemcrea);

        itemrechnum.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        itemrechnum.setText("recherche sur l'id");
        itemrechnum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        itemrechnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemrechnumActionPerformed(evt);
            }
        });
        menutaxi.add(itemrechnum);

        itemrechdescription.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        itemrechdescription.setText("recherche description");
        itemrechdescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        itemrechdescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemrechdescriptionActionPerformed(evt);
            }
        });
        menutaxi.add(itemrechdescription);

        itemrechimmatricule.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        itemrechimmatricule.setText("recherche immatriculation");
        itemrechimmatricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemrechimmatriculeActionPerformed(evt);
            }
        });
        menutaxi.add(itemrechimmatricule);

        jMenuBar1.add(menutaxi);

        menulocation.setBackground(new java.awt.Color(255, 255, 0));
        menulocation.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        menulocation.setText("Location");

        itemcrealocation.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        itemcrealocation.setText("crée lacation");
        itemcrealocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemcrealocationActionPerformed(evt);
            }
        });
        menulocation.add(itemcrealocation);

        jMenuBar1.add(menulocation);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemcreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemcreaActionPerformed
      cardl.show(this.getContentPane(), "card3");
    }//GEN-LAST:event_itemcreaActionPerformed

    private void itemrechnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemrechnumActionPerformed
        cardl.show(this.getContentPane(), "cardrechid");
    }//GEN-LAST:event_itemrechnumActionPerformed

    private void itemrechimmatriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemrechimmatriculeActionPerformed
       cardl.show(this.getContentPane(), "cardrechimmatriculation");
    }//GEN-LAST:event_itemrechimmatriculeActionPerformed

    private void itemrechdescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemrechdescriptionActionPerformed
        cardl.show(this.getContentPane(), "card5");
    }//GEN-LAST:event_itemrechdescriptionActionPerformed

    private void itemcrealocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemcrealocationActionPerformed
       cardl.show(this.getContentPane(), "card7");
    }//GEN-LAST:event_itemcrealocationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionTaxi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionTaxi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionTaxi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionTaxi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionTaxi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private taxi_graphique.CreaLocation creaLocation1;
    private taxi_graphique.CreaTaxi creaTaxi1;
    private taxi_graphique.fond fond1;
    private javax.swing.JMenuItem itemcrea;
    private javax.swing.JMenuItem itemcrealocation;
    private javax.swing.JMenuItem itemrechdescription;
    private javax.swing.JMenuItem itemrechimmatricule;
    private javax.swing.JMenuItem itemrechnum;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menulocation;
    private javax.swing.JMenu menutaxi;
    private taxi_graphique.RechDescription rechDescription1;
    private taxi_graphique.Rechidtaxi rechidtaxi1;
    private taxi_graphique.Rechimmatriculation rechimmatriculation1;
    // End of variables declaration//GEN-END:variables
}
