/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taxi_graphique;

import javax.swing.JOptionPane;
import taxi_DAO.Vehicule_taxi_DAO;
import taxi.metier.Vehicule_taxi;

/**
/**
 *
 * @author Kamgo
 */
public class Rechidtaxi extends javax.swing.JPanel {

    /**
     * Creates new form CreaCli
     */
     Vehicule_taxi_DAO taxiDAO=null;
    Vehicule_taxi taxi=null;
    public Rechidtaxi() {
        initComponents();
    }

    public void setTaxiDAO(Vehicule_taxi_DAO taxiDAO){
        this.taxiDAO=taxiDAO;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblimmatriculation = new javax.swing.JLabel();
        llblnumtaxi = new javax.swing.JLabel();
        lblcarburant = new javax.swing.JLabel();
        lblprixkm = new javax.swing.JLabel();
        lbldescription = new javax.swing.JLabel();
        txtnumtaxi = new javax.swing.JTextField();
        txtcarburant = new javax.swing.JTextField();
        txtimmatriculation = new javax.swing.JTextField();
        txtprixkm = new javax.swing.JTextField();
        txtdescription = new javax.swing.JTextField();
        btmaj = new javax.swing.JButton();
        btrech = new javax.swing.JButton();
        btdel = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 255, 255));

        lblimmatriculation.setText("immatriculation");

        llblnumtaxi.setText("numéro du taxi");

        lblcarburant.setText("carburant");

        lblprixkm.setText("prixkm");

        lbldescription.setText("description");

        txtnumtaxi.setMinimumSize(new java.awt.Dimension(50, 20));
        txtnumtaxi.setNextFocusableComponent(txtimmatriculation);
        txtnumtaxi.setPreferredSize(new java.awt.Dimension(150, 30));
        txtnumtaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumtaxiActionPerformed(evt);
            }
        });

        txtcarburant.setMinimumSize(new java.awt.Dimension(50, 20));
        txtcarburant.setNextFocusableComponent(txtprixkm);
        txtcarburant.setPreferredSize(new java.awt.Dimension(150, 30));

        txtimmatriculation.setMinimumSize(new java.awt.Dimension(50, 20));
        txtimmatriculation.setNextFocusableComponent(txtcarburant);
        txtimmatriculation.setPreferredSize(new java.awt.Dimension(150, 30));

        txtprixkm.setMinimumSize(new java.awt.Dimension(50, 20));
        txtprixkm.setNextFocusableComponent(txtdescription);
        txtprixkm.setPreferredSize(new java.awt.Dimension(150, 30));

        txtdescription.setMinimumSize(new java.awt.Dimension(50, 20));
        txtdescription.setPreferredSize(new java.awt.Dimension(150, 30));

        btmaj.setText("maj");
        btmaj.setPreferredSize(new java.awt.Dimension(150, 30));
        btmaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmajActionPerformed(evt);
            }
        });

        btrech.setText("Rechercher");
        btrech.setPreferredSize(new java.awt.Dimension(150, 30));
        btrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrechActionPerformed(evt);
            }
        });

        btdel.setText("Effacer");
        btdel.setPreferredSize(new java.awt.Dimension(150, 30));
        btdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(llblnumtaxi)
                            .addComponent(lblimmatriculation)
                            .addComponent(lblprixkm)
                            .addComponent(lbldescription))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprixkm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcarburant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnumtaxi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtimmatriculation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblcarburant))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btrech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btmaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(btdel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(llblnumtaxi)
                    .addComponent(txtnumtaxi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblimmatriculation)
                    .addComponent(txtimmatriculation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcarburant)
                    .addComponent(txtcarburant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprixkm)
                    .addComponent(txtprixkm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldescription)
                    .addComponent(txtdescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btdel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btrech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtnumtaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumtaxiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumtaxiActionPerformed

    private void btmajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmajActionPerformed
     try{  
       int numtaxi=Integer.parseInt(txtnumtaxi.getText());
       String immatriculation=txtimmatriculation.getText();
       String carburant=txtcarburant.getText();
           int prixkm=Integer.parseInt(txtprixkm.getText());
       String description= txtdescription.getText();
       
       Vehicule_taxi taxi = new Vehicule_taxi(numtaxi,immatriculation,carburant,prixkm,description);
       taxiDAO.update(taxi);
       JOptionPane.showMessageDialog(this,"taxi mis à jour","succès",JOptionPane.INFORMATION_MESSAGE);
       
     }
     catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
     }
               
    }//GEN-LAST:event_btmajActionPerformed

    private void btrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrechActionPerformed
        try{
             int numtaxi=Integer.parseInt(txtnumtaxi.getText());
             taxi=taxiDAO.read(numtaxi);
             txtimmatriculation.setText(taxi.getImmatriculation());
             txtcarburant.setText(taxi.getCarburant());
             txtprixkm.setText(""+taxi.getPrixkm());
             txtdescription.setText(taxi.getDescription());
           
             JOptionPane.showMessageDialog(this,"taxi trouvé","succès",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_btrechActionPerformed

    private void btdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdelActionPerformed
        try{
             int numtaxi=Integer.parseInt(txtnumtaxi.getText());
             taxiDAO.delete(taxi);
             txtnumtaxi.setText("");
             txtimmatriculation.setText("");
             txtcarburant.setText("");
             txtprixkm.setText("");
             txtdescription.setText("");
            
             JOptionPane.showMessageDialog(this,"taxi effacé","succès",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_btdelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdel;
    private javax.swing.JButton btmaj;
    private javax.swing.JButton btrech;
    private javax.swing.JLabel lblcarburant;
    private javax.swing.JLabel lbldescription;
    private javax.swing.JLabel lblimmatriculation;
    private javax.swing.JLabel lblprixkm;
    private javax.swing.JLabel llblnumtaxi;
    private javax.swing.JTextField txtcarburant;
    private javax.swing.JTextField txtdescription;
    private javax.swing.JTextField txtimmatriculation;
    private javax.swing.JTextField txtnumtaxi;
    private javax.swing.JTextField txtprixkm;
    // End of variables declaration//GEN-END:variables
}
