/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taxi_graphique;

import dbconnect.dbconnexion;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import taxi_DAO.Location_taxi_DAO;
import taxi_DAO.Client_taxi_DAO;
import taxi_DAO.AdresseDAO;
import taxi_DAO.Vehicule_taxi_DAO;
import javax.swing.table.DefaultTableModel;
import taxi.metier.Location_taxi;
import java.util.Vector;
/**
 *
 * @author Kamgo
 */
public class Rechloc extends javax.swing.JPanel {

    /**
     * Creates new form Rechlocationtaxi
     */
    
   Location_taxi_DAO locationDAO=null;
   DefaultTableModel dft1 = new DefaultTableModel();
  
    public Rechloc() {
        initComponents();
        dft1.addColumn("numlocation");
        dft1.addColumn("dateloc");
        dft1.addColumn("kmtotal");
        dft1.addColumn("acompte");
        dft1.addColumn("total");
        dft1.addColumn("idclient");
        dft1.addColumn("idtaxi");
        dft1.addColumn("idadrdebut");
        dft1.addColumn("idadrfin");
        jTable1.setModel(dft1);

        
    }
   
   

    public void setTaxiDAO(Location_taxi_DAO locationDAO){
        this.locationDAO=locationDAO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblidtaxi = new javax.swing.JLabel();
        txtidtaxi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        lblidtaxi.setText("idtaxi");

        txtidtaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidtaxiActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblidtaxi)
                        .addGap(92, 92, 92)
                        .addComponent(txtidtaxi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidtaxi)
                    .addComponent(txtidtaxi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtidtaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidtaxiActionPerformed
       try{ 
       int idtaxi=Integer.parseInt(txtidtaxi.getText());
        List<Location_taxi> alc= locationDAO.rechloc(idtaxi);
        int nr = dft1.getRowCount();
        for(int i=nr-1;i>=0;i--)dft1.removeRow(i);
        for(Location_taxi location:alc){
            Vector v = new Vector();
            v.add(location.getIdloc());
            v.add(location.getDateloc());
            v.add(location.getKmtotal());
            v.add(location.getAcompte());
            v.add(location.getTotal());
            v.add(location.getIdclient());
             v.add(location.getIdtaxi());
              v.add(location.getIdadrdebuit());
               v.add(location.getIdadrfin());
            dft1.addRow(v);
           
        }
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_txtidtaxiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblidtaxi;
    private javax.swing.JTextField txtidtaxi;
    // End of variables declaration//GEN-END:variables
}
